### ISSUE TITLE
The 2.4.0 gem release is missing files from lib/benchmark/ips/job

### ISSUE THREAD

**Issue by britishtea** [evanphx/benchmark-ips#59]
Files required in `lib/benchmark/ips.rb` are not included in the released gem:

```
$ irb
irb(main):001:0> require "benchmark/ips"
LoadError: cannot load such file -- benchmark/ips/job/entry
	from /Users/jip/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jip/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/jip/.gem/ruby/2.3.0/gems/benchmark-ips-2.4.0/lib/benchmark/ips.rb:5:in `<top (required)>'
	from /Users/jip/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /Users/jip/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /Users/jip/.rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from (irb):1
	from /Users/jip/.rubies/ruby-2.3.0/bin/irb:11:in `<main>'
irb(main):002:0> 

```

```
$ tree (dirname (gem which benchmark/ips))
/Users/jip/.gem/ruby/2.3.0/gems/benchmark-ips-2.4.0/lib/benchmark
├── compare.rb
├── ips
│   ├── job.rb
│   └── report.rb
├── ips.rb
└── timing.rb

1 directory, 5 files
```

Unfortunately, I'm not familiar enough with `hoe` to make a pull request.

**Comment by evanphx** [comment]
Whoops! Sorry about that! All fixed now, thanks for reporting it!
